import os

env = Environment()

godot_cpp = "../godot-cpp"

env.Append(CPPPATH=[
    ".",
    godot_cpp + "/include",
    godot_cpp + "/gen/include",
    godot_cpp + "/gdextension",
])

env.Append(LIBPATH=[godot_cpp + "/bin"])
env.Append(LIBS=["godot-cpp.linux.template_debug.x86_64"])
env.Append(CXXFLAGS=["-std=c++17"])
env.Append(LINKFLAGS=["-shared"])

sources = (
    Glob("register_types.cpp") +
    Glob("Core/*.cpp") +
    Glob("Entity/Player/*.cpp") +
    Glob("Input/*.cpp") +
    Glob("Gameplay/Inventory/*.cpp") +
    Glob("Gameplay/Stats/*.cpp") 
)

target = ARGUMENTS.get("target", "debug")
library_name = "../bin/libplayer." + target + ".so"

library = env.SharedLibrary(
    target=library_name,
    source=sources
)

Default(library)
