import os

env = Environment()

godot_cpp = "../godot-cpp"

env.Append(CPPPATH=[
    ".",
    godot_cpp + "/include",
    godot_cpp + "/gen/include",
    godot_cpp + "/gdextension",
])

env.Append(LIBPATH=[
    godot_cpp + "/bin"
])

env.Append(LIBS=[
    "godot-cpp.linux.template_debug.x86_64"
])

env.Append(CXXFLAGS=[
    "-std=c++17",
])

env.Append(LINKFLAGS=[
    "-shared"
])

sources = Glob("register_types.cpp") + Glob("Player/*.cpp") + Glob("Core/*.cpp") + Glob("Gameplay/*.cpp")

target = "debug"
if ARGUMENTS.get("target"):
    target = ARGUMENTS.get("target")

library_name = "../bin/libplayer." + target + ".so"
library = env.SharedLibrary(
    target=library_name,
    source=sources
)
Default(library)
